Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
files = sorted(glob.glob('../../data/surface-meteorology/*/*/*/*.nc'))

ds = xr.open_mfdataset(files[-60:])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m files [38;5;241m=[39m [38;5;28msorted[39m(glob[38;5;241m.[39mglob([38;5;124m'[39m[38;5;124m../../data/surface-meteorology/*/*/*/*.nc[39m[38;5;124m'[39m))
[0;32m----> 3[0m ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_mfdataset[49m[43m([49m[43mfiles[49m[43m[[49m[38;5;241;43m-[39;49m[38;5;241;43m60[39;49m[43m:[49m[43m][49m[43m)[49m

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/xarray/backends/api.py:1597[0m, in [0;36mopen_mfdataset[0;34m(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)[0m
[1;32m   1594[0m paths [38;5;241m=[39m _find_absolute_paths(paths, engine[38;5;241m=[39mengine, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1596[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m paths:
[0;32m-> 1597[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m"[39m[38;5;124mno files to open[39m[38;5;124m"[39m)
[1;32m   1599[0m paths1d: [38;5;28mlist[39m[[38;5;28mstr[39m [38;5;241m|[39m ReadBuffer]
[1;32m   1600[0m [38;5;28;01mif[39;00m combine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mnested[39m[38;5;124m"[39m:

[0;31mOSError[0m: no files to open

