Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cat_url = 'https://thredds.crocus-urban.org/thredds/catalog/neiu-mrrpro-a1/catalog.html'
cat = TDSCatalog(cat_url)
print(list(cat.datasets.keys()))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m cat_url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://thredds.crocus-urban.org/thredds/catalog/neiu-mrrpro-a1/catalog.html[39m[38;5;124m'[39m
[0;32m----> 2[0m cat [38;5;241m=[39m [43mTDSCatalog[49m[43m([49m[43mcat_url[49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m([38;5;28mlist[39m(cat[38;5;241m.[39mdatasets[38;5;241m.[39mkeys()))

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/siphon/catalog.py:289[0m, in [0;36mTDSCatalog.__init__[0;34m(self, catalog_url)[0m
[1;32m    287[0m [38;5;66;03m# get catalog.xml file[39;00m
[1;32m    288[0m resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msession[38;5;241m.[39mget(catalog_url)
[0;32m--> 289[0m [43mresp[49m[38;5;241;43m.[39;49m[43mraise_for_status[49m[43m([49m[43m)[49m
[1;32m    291[0m [38;5;66;03m# top level server url[39;00m
[1;32m    292[0m [38;5;28mself[39m[38;5;241m.[39mcatalog_url [38;5;241m=[39m resp[38;5;241m.[39murl

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/requests/models.py:1024[0m, in [0;36mResponse.raise_for_status[0;34m(self)[0m
[1;32m   1019[0m     http_error_msg [38;5;241m=[39m (
[1;32m   1020[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mstatus_code[38;5;132;01m}[39;00m[38;5;124m Server Error: [39m[38;5;132;01m{[39;00mreason[38;5;132;01m}[39;00m[38;5;124m for url: [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39murl[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m   1021[0m     )
[1;32m   1023[0m [38;5;28;01mif[39;00m http_error_msg:
[0;32m-> 1024[0m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response[38;5;241m=[39m[38;5;28mself[39m)

[0;31mHTTPError[0m: 502 Server Error: Bad Gateway for url: https://thredds.crocus-urban.org/thredds/catalog/neiu-mrrpro-a1/catalog.html

